services:
  postgres:
    image: postgres:12.4
    volumes:
      - ./postgres.bkp:/docker-entrypoint-initdb.d/postgres.sql
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coud-group
    ports:
      - "5432:5432"